// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: blog.proto

package server

import (
	"context"

	"blog-system-zero/app/blog/internal/logic"
	"blog-system-zero/app/blog/internal/svc"
	"blog-system-zero/app/blog/types/blog"
)

type BlogServiceServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedBlogServiceServer
}

func NewBlogServiceServer(svcCtx *svc.ServiceContext) *BlogServiceServer {
	return &BlogServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *BlogServiceServer) CreatePost(ctx context.Context, in *blog.CreatePostRequest) (*blog.CreatePostResponse, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *BlogServiceServer) GetPost(ctx context.Context, in *blog.GetPostRequest) (*blog.GetPostResponse, error) {
	l := logic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}

func (s *BlogServiceServer) GetPosts(ctx context.Context, in *blog.GetPostsRequest) (*blog.GetPostsResponse, error) {
	l := logic.NewGetPostsLogic(ctx, s.svcCtx)
	return l.GetPosts(in)
}

func (s *BlogServiceServer) UpdatePost(ctx context.Context, in *blog.UpdatePostRequest) (*blog.BaseResponse, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *BlogServiceServer) DeletePost(ctx context.Context, in *blog.DeletePostRequest) (*blog.BaseResponse, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

func (s *BlogServiceServer) CreateComment(ctx context.Context, in *blog.CreateCommentRequest) (*blog.BaseResponse, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *BlogServiceServer) GetComments(ctx context.Context, in *blog.GetCommentsRequest) (*blog.GetCommentsResponse, error) {
	l := logic.NewGetCommentsLogic(ctx, s.svcCtx)
	return l.GetComments(in)
}

func (s *BlogServiceServer) DeleteComment(ctx context.Context, in *blog.DeleteCommentRequest) (*blog.BaseResponse, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}
