// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: blog.proto

package blogservice

import (
	"context"

	"blog-system-zero/app/blog/types/blog"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResponse         = blog.BaseResponse
	CommentInfo          = blog.CommentInfo
	CreateCommentRequest = blog.CreateCommentRequest
	CreatePostRequest    = blog.CreatePostRequest
	CreatePostResponse   = blog.CreatePostResponse
	DeleteCommentRequest = blog.DeleteCommentRequest
	DeletePostRequest    = blog.DeletePostRequest
	GetCommentsRequest   = blog.GetCommentsRequest
	GetCommentsResponse  = blog.GetCommentsResponse
	GetPostRequest       = blog.GetPostRequest
	GetPostResponse      = blog.GetPostResponse
	GetPostsRequest      = blog.GetPostsRequest
	GetPostsResponse     = blog.GetPostsResponse
	PostInfo             = blog.PostInfo
	UpdatePostRequest    = blog.UpdatePostRequest
	UserInfo             = blog.UserInfo

	BlogService interface {
		CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
		GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
		GetPosts(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error)
		UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*BaseResponse, error)
		DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*BaseResponse, error)
		CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*BaseResponse, error)
		GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error)
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	}

	defaultBlogService struct {
		cli zrpc.Client
	}
)

func NewBlogService(cli zrpc.Client) BlogService {
	return &defaultBlogService{
		cli: cli,
	}
}

func (m *defaultBlogService) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

func (m *defaultBlogService) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.GetPost(ctx, in, opts...)
}

func (m *defaultBlogService) GetPosts(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.GetPosts(ctx, in, opts...)
}

func (m *defaultBlogService) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

func (m *defaultBlogService) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

func (m *defaultBlogService) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultBlogService) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.GetComments(ctx, in, opts...)
}

func (m *defaultBlogService) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}
