// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/auth/login",
					Handler: LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/auth/register",
					Handler: RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/comments",
					Handler: CreateCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/comments/:id",
					Handler: DeleteCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/post/:id",
					Handler: GetPostHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/post/:id",
					Handler: DeletePostHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/post/:id/comments",
					Handler: GetCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/posts",
					Handler: GetPostsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/posts",
					Handler: getPostHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/posts/:id",
					Handler: UpdatePostHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/profile",
					Handler: GetProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
