// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResponse struct {
	Code    int32       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CommentInfo struct {
	ID       uint64   `json:"id"`
	Content  string   `json:"content"`
	UserId   uint64   `json:"user_id"`
	PostId   uint64   `json:"postId"`
	User     UserInfo `json:"user"`
	CreateAt string   `json:"create_at"`
}

type CreateCommentRequest struct {
	PostId  uint64 `json:"postId"`
	Content string `json:"content"`
}

type CreatePostRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type LoginRequest struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

type PostInfo struct {
	ID       uint64   `json:"id"`
	Title    string   `json:"title"`
	Content  string   `json:"content"`
	UserId   string   `json:"user_id"`
	User     UserInfo `json:"user"`
	CreateAt string   `json:"create_at"`
	UpdateAt string   `json:"update_at"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdatePostRequest struct {
	Title   string `json:"title,optional"`
	Content string `json:"content,optional"`
}

type UserInfo struct {
	ID       uint64 `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	CreateAt string `json:"create_at"`
	UpdateAt string `json:"update_at"`
}
